version: '3.8'

x-django: &django
  build:
    context: .
    dockerfile: ./docker/django/Dockerfile
  restart: always
  image: "${COMPOSE_IMAGES_PREFIX}_prod"
  depends_on:
    - postgres
  volumes:
    - ./src:/opt/project/src:cached
    - ./data/prod:/data:z
    - static:/data/staticfiles/
    - media:/data/media/
  env_file:
    - ./.env

services:
  django:
    <<: *django
    command: prod
  celeryworker:
    <<: *django
    command: celery worker -l INFO
  celerybeat:
    <<: *django
    command: celery beat -l INFO
  flower:
    image: mher/flower:0.9.7
    command: "flower --broker=${REDIS_URL} --port=5555 --url-prefix=flower --basic_auth=${CELERY_FLOWER_USER}:${CELERY_FLOWER_PASSWORD}"
    depends_on:
      - redis
    env_file:
      - ./.env
  redis:
    image: redis:6.0
    restart: always
  postgres:
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    image: "${COMPOSE_IMAGES_PREFIX}_prod_postgres"
    restart: always
    volumes:
      - prod_postgres:/var/lib/postgresql/data:Z
      - prod_backups:/backups:z
    env_file:
      - ./.env
  caddy:
    build:
      context: .
      dockerfile: ./docker/caddy/Dockerfile
    image: "${COMPOSE_IMAGES_PREFIX}_prod_caddy"
    restart: unless-stopped
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - prod_caddy:/data
      - static:/static:ro
      - media:/media
      - caddy_config:/config
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile
    env_file:
      - ./.env
    depends_on:
      - django

volumes:
  prod_postgres:
  prod_backups:
  prod_caddy:
  media:
  static:
  caddy_config:
