#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
python /app/manage.py migrate

# /usr/local/bin/gunicorn cronsy.asgi --bind 0.0.0.0:8000 --chdir=/app -k uvicorn.workers.UvicornWorker
/usr/local/bin/gunicorn cronsy.wsgi --bind 0.0.0.0:8000 --chdir=/app
